# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import enum
import typing
__all__ = [
    "Aligner",
    "Mapping",
    "MappingIterator",
    "Minimizer",
    "MinimizerSketcher",
    "Preset",
    "RandstrobeSketcher",
    "SyncmerSketcher",
]

@typing.final
class Aligner:
    r"""
    The core aligner object. 
    It encapsulates the `RustAligner` from `rammap-core` and executes the alignments.
    """
    def __new__(cls, targets: typing.Sequence[tuple[bytes, bytes]], preset: Preset = Preset.MapOnt, do_cigar: builtins.bool = True, do_cs: builtins.bool = True, do_md: builtins.bool = True) -> Aligner:
        r"""
        Create a new aligner instance with predefined target genomes.
        Using Python `bytes` for genomic data sidesteps UTF-8 validation overhead present in normal strings.
        """
    def map(self, query_name: bytes, query_seq: bytes) -> MappingIterator:
        r"""
        Maps a single query sequence sequentially to the targets.
        """
    def map_batch(self, queries: typing.Sequence[tuple[bytes, bytes]]) -> builtins.list[MappingIterator]:
        r"""
        Performs zero-copy, highly parallelized batch alignments mapping over `queries`.
        
        To bypass the GIL and utilize multiple threads for parallelism (via Rayon), we must avoid executing
        native Python code or invoking Python objects during the mapping loops. `Bound<'py, PyBytes>` offers zero-copy
        memory pointers to the Python memory regions, however, `Bound` relies on the GIL. We drop the GIL using `py.detach(|| ...)`
        but must carefully encapsulate the memory bounds outside the Rayon threads using Raw Pointers.
        """

@typing.final
class Mapping:
    r"""
    Python representation of an alignment `Mapping`.
    By wrapping `RustMapping` internally, we enforce lazy-evaluation semantics.
    The fields of the underlying struct are mapped via Python property getters.
    """
    @property
    def target_name(self) -> bytes:
        r"""
        Return the target name as Python `bytes`.
        """
    @property
    def target_start(self) -> builtins.int: ...
    @property
    def target_end(self) -> builtins.int: ...
    @property
    def target_len(self) -> builtins.int: ...
    @property
    def query_start(self) -> builtins.int: ...
    @property
    def query_end(self) -> builtins.int: ...
    @property
    def strand(self) -> builtins.int: ...
    @property
    def score(self) -> builtins.int: ...
    @property
    def mapq(self) -> builtins.int: ...
    @property
    def is_primary(self) -> builtins.bool: ...
    @property
    def cigar(self) -> typing.Optional[bytes]:
        r"""
        Returns the optional CIGAR string as a lazy byte array.
        """
    @property
    def cs(self) -> typing.Optional[bytes]:
        r"""
        Returns the optional cs string as a lazy byte array.
        """
    @property
    def md(self) -> typing.Optional[bytes]:
        r"""
        Returns the optional MD string as a lazy byte array.
        """

@typing.final
class MappingIterator:
    r"""
    A lazy iterator that yields Mapping wrapper objects on demand.
    Instead of allocating a `Vec<Mapping>` (which copies the mappings and increases peak memory),
    we hold an iterator of Rust mappings and materialize Python wrapper objects only when requested via `next()`.
    """
    def __iter__(self) -> MappingIterator: ...
    def __next__(self) -> typing.Optional[Mapping]: ...

@typing.final
class Minimizer:
    r"""
    Python wrapper for the core `Minimizer` struct.
    We #[derive(Clone)] so it can be returned easily as a vector to Python.
    The attributes `x` and `y` are directly exposed as read-only properties to avoid Python getter overhead.
    """
    @property
    def x(self) -> builtins.int: ...
    @property
    def y(self) -> builtins.int: ...

@typing.final
class MinimizerSketcher:
    r"""
    A Sketcher for Minimizers.
    This exposes the underlying `MinimizerSketcher` from the Rust core.
    """
    def __new__(cls, k: builtins.int, w: builtins.int) -> MinimizerSketcher:
        r"""
        Initialize a new MinimizerSketcher with k-mer size `k` and window size `w`.
        The Rust struct fields are directly instantiated as the Rust core does not expose a `new` function for this type.
        """
    def sketch(self, seq: bytes) -> builtins.list[Minimizer]:
        r"""
        Extract seeds/minimizers from a byte string sequence.
        Bytes (`&Bound<'_, PyBytes>`) are preferred here instead of `String` for zero-copy FFI when interfacing with Python `bytes`.
        """

@typing.final
class RandstrobeSketcher:
    r"""
    A Sketcher for Randstrobes.
    """
    def __new__(cls, k: builtins.int, w_min: builtins.int, w_max: builtins.int) -> RandstrobeSketcher: ...
    def sketch(self, seq: bytes) -> builtins.list[Minimizer]: ...

@typing.final
class SyncmerSketcher:
    r"""
    A Sketcher for Syncmers.
    """
    def __new__(cls, k: builtins.int, s: builtins.int) -> SyncmerSketcher: ...
    def sketch(self, seq: bytes) -> builtins.list[Minimizer]: ...

@typing.final
class Preset(enum.Enum):
    r"""
    The mapping presets available in `rammap`.
    Exposed as a Python Enum for seamless instantiation in Python.
    """
    MapOnt = ...
    MapHifi = ...
    Sr = ...
    Splice = ...
    Asm5 = ...
    Asm10 = ...
    Asm20 = ...
    MapPb = ...

