# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import enum
import os
import pathlib
import typing

__all__ = [
    "Aligner",
    "AlignmentParams",
    "ChainingParams",
    "CigarElement",
    "CigarOp",
    "FastaStreamer",
    "FastqStreamer",
    "FastxReader",
    "FilteringParams",
    "Index",
    "MapOptions",
    "Mapping",
    "MappingIterator",
    "Minimizer",
    "MinimizerSketcher",
    "PairedEndParams",
    "Preset",
    "RandstrobeSketcher",
    "Record",
    "ScoringParams",
    "SeedingParams",
    "Strand",
    "SyncmerSketcher",
    "parse_fasta_bytes",
    "read_fasta",
]

@typing.final
class Aligner:
    r"""
    The `Aligner` orchestrates the alignment process.

    It encapsulates the alignment configuration and the index to map query sequences against reference targets.

    Examples:
        >>> from rammappy import Index, Aligner, Preset
        >>> index = Index.build([(b"target1", b"ATGC...")])
        >>> aligner = Aligner(index, preset=Preset.MapOnt)
        >>> for mapping in aligner.map(b"query1", b"ATGC..."):
        ...     print(mapping.score)
    """

    @property
    def options(self) -> MapOptions:
        r"""
        Returns the sequence names in the index.

        Returns:
            list[str]: The list of sequence names.
        Get the current mapping options.

        Returns:
            MapOptions: A copy of the current mapping options.
        """

    @options.setter
    def options(self, value: MapOptions) -> None:
        r"""
        Set the mapping options.

        Args:
            opts (MapOptions): The new mapping options to apply.
        """

    @property
    def seq_names(self) -> builtins.list[builtins.str]: ...
    def __new__(
        cls,
        index: Index,
        preset: typing.Optional[Preset] = Preset.MapOnt,
        do_cigar: builtins.bool = True,
        do_cs: builtins.bool = True,
        do_md: builtins.bool = True,
    ) -> Aligner:
        r"""
        Create a new aligner instance using an already built index.

        Args:
            index (Index): The built index object.
            preset (Preset): The preset configuration (e.g. `Preset.MapOnt`). Defaults to `Preset.MapOnt`.
            do_cigar (bool): Whether to compute CIGAR strings. Defaults to `True`.
            do_cs (bool): Whether to compute `cs` tags. Defaults to `True`.
            do_md (bool): Whether to compute `md` tags. Defaults to `True`.

        Returns:
            Aligner: The initialized aligner object.
        """

    @staticmethod
    def from_fasta(
        path: builtins.str | os.PathLike | pathlib.Path,
        preset: typing.Optional[Preset] = Preset.MapOnt,
    ) -> Aligner:
        r"""
        Create an aligner from a FASTA file.

        Args:
            path (os.PathLike): The file path to the FASTA file.
            preset (Preset): The preset configuration (e.g. `Preset.MapOnt`). Defaults to `Preset.MapOnt`.

        Returns:
            Aligner: The initialized aligner object.
        """

    @staticmethod
    def from_index(
        path: builtins.str | os.PathLike | pathlib.Path,
        preset: typing.Optional[Preset] = Preset.MapOnt,
    ) -> Aligner:
        r"""
        Create an aligner from an index file.

        Args:
            path (os.PathLike): The file path to the saved index file.
            preset (Preset): The preset configuration (e.g. `Preset.MapOnt`). Defaults to `Preset.MapOnt`.

        Returns:
            Aligner: The initialized aligner object.
        """

    def map(self, query_name: bytes, query_seq: bytes) -> MappingIterator:
        r"""
        Maps a single query sequence sequentially to the targets.

        Args:
            query_name (bytes): The name of the query sequence.
            query_seq (bytes): The query sequence.

        Returns:
            MappingIterator: An iterator over the generated mappings.
        """

    def map_batch(
        self, queries: typing.Sequence[tuple[bytes, bytes]]
    ) -> builtins.list[MappingIterator]:
        r"""
        Performs highly parallelized batch alignments mapping over multiple queries.

        Bypasses the GIL to utilize multiple threads for parallelism (via Rayon).

        Args:
            queries (list[tuple[bytes, bytes]]): A list of tuples containing `(name, sequence)` as bytes.

        Returns:
            list[MappingIterator]: A list of iterators, one for each query sequence.
        """

    def load_junctions_bed(self, path: builtins.str | os.PathLike | pathlib.Path) -> None:
        r"""
        Load splice junctions from a BED file.

        Args:
            path (os.PathLike | str): Path to the BED file.
        """

    def load_junctions_spsc(
        self,
        path: builtins.str | os.PathLike | pathlib.Path,
        scale: typing.Optional[builtins.float] = None,
    ) -> None:
        r"""
        Load splice junctions from a SPSC file.

        Args:
            path (os.PathLike | str): Path to the SPSC file.
            scale (float | None): Optional scaling factor.
        """

    def seq(
        self,
        name: builtins.str,
        start: typing.Optional[builtins.int] = None,
        end: typing.Optional[builtins.int] = None,
    ) -> builtins.str:
        r"""
        Returns the sequence for a given target name.

        Args:
            name (str): The name of the target sequence.
            start (int, optional): The 0-based start coordinate. Defaults to 0.
            end (int, optional): The 0-based end coordinate. Defaults to the end of the sequence.

        Returns:
            str: The requested sequence.

        Raises:
            ValueError: If the sequence name is not found in the index.
        """

@typing.final
class AlignmentParams:
    @property
    def zdrop(self) -> builtins.int: ...
    @zdrop.setter
    def zdrop(self, value: builtins.int) -> None: ...
    @property
    def zdrop_inv(self) -> builtins.int: ...
    @zdrop_inv.setter
    def zdrop_inv(self, value: builtins.int) -> None: ...
    @property
    def end_bonus(self) -> builtins.int: ...
    @end_bonus.setter
    def end_bonus(self, value: builtins.int) -> None: ...
    @property
    def max_sw_mat(self) -> builtins.int: ...
    @max_sw_mat.setter
    def max_sw_mat(self, value: builtins.int) -> None: ...
    @property
    def min_dp_max(self) -> builtins.int: ...
    @min_dp_max.setter
    def min_dp_max(self, value: builtins.int) -> None: ...
    @property
    def min_dp_len(self) -> builtins.int: ...
    @min_dp_len.setter
    def min_dp_len(self, value: builtins.int) -> None: ...
    @property
    def anchor_ext_len(self) -> builtins.int: ...
    @anchor_ext_len.setter
    def anchor_ext_len(self, value: builtins.int) -> None: ...
    @property
    def anchor_ext_shift(self) -> builtins.int: ...
    @anchor_ext_shift.setter
    def anchor_ext_shift(self, value: builtins.int) -> None: ...
    @property
    def max_clip_ratio(self) -> builtins.float: ...
    @max_clip_ratio.setter
    def max_clip_ratio(self, value: builtins.float) -> None: ...

@typing.final
class ChainingParams:
    @property
    def min_cnt(self) -> builtins.int: ...
    @min_cnt.setter
    def min_cnt(self, value: builtins.int) -> None: ...
    @property
    def min_chain_score(self) -> builtins.int: ...
    @min_chain_score.setter
    def min_chain_score(self, value: builtins.int) -> None: ...
    @property
    def max_gap(self) -> builtins.int: ...
    @max_gap.setter
    def max_gap(self, value: builtins.int) -> None: ...
    @property
    def max_gap_ref(self) -> builtins.int: ...
    @max_gap_ref.setter
    def max_gap_ref(self, value: builtins.int) -> None: ...
    @property
    def max_dist_x(self) -> builtins.int: ...
    @max_dist_x.setter
    def max_dist_x(self, value: builtins.int) -> None: ...
    @property
    def max_dist_y(self) -> builtins.int: ...
    @max_dist_y.setter
    def max_dist_y(self, value: builtins.int) -> None: ...
    @property
    def bandwidth(self) -> builtins.int: ...
    @bandwidth.setter
    def bandwidth(self, value: builtins.int) -> None: ...
    @property
    def bandwidth_long(self) -> builtins.int: ...
    @bandwidth_long.setter
    def bandwidth_long(self, value: builtins.int) -> None: ...
    @property
    def max_chain_skip(self) -> builtins.int: ...
    @max_chain_skip.setter
    def max_chain_skip(self, value: builtins.int) -> None: ...
    @property
    def max_chain_iter(self) -> builtins.int: ...
    @max_chain_iter.setter
    def max_chain_iter(self, value: builtins.int) -> None: ...
    @property
    def chn_pen_gap(self) -> builtins.float: ...
    @chn_pen_gap.setter
    def chn_pen_gap(self, value: builtins.float) -> None: ...
    @property
    def chn_pen_skip(self) -> builtins.float: ...
    @chn_pen_skip.setter
    def chn_pen_skip(self, value: builtins.float) -> None: ...
    @property
    def chain_gap_scale(self) -> builtins.float: ...
    @chain_gap_scale.setter
    def chain_gap_scale(self, value: builtins.float) -> None: ...
    @property
    def rmq_rescue_size(self) -> builtins.int: ...
    @rmq_rescue_size.setter
    def rmq_rescue_size(self, value: builtins.int) -> None: ...
    @property
    def rmq_rescue_ratio(self) -> builtins.float: ...
    @rmq_rescue_ratio.setter
    def rmq_rescue_ratio(self, value: builtins.float) -> None: ...
    @property
    def rmq_inner_dist(self) -> builtins.int: ...
    @rmq_inner_dist.setter
    def rmq_inner_dist(self, value: builtins.int) -> None: ...
    @property
    def rmq_size_cap(self) -> builtins.int: ...
    @rmq_size_cap.setter
    def rmq_size_cap(self, value: builtins.int) -> None: ...

@typing.final
class CigarElement:
    r"""
    Structured CIGAR operation element (length and operation type).

    Attributes:
        len (int): Operation length.
        op (CigarOp): Operation type enum.
    """

    @property
    def len(self) -> builtins.int: ...
    @property
    def op(self) -> CigarOp: ...

@typing.final
class FastaStreamer:
    r"""
    Streaming FASTA parser. Push bytes via `push`; pop completed
    `(name, seq)` pairs via `next_record`; flush the
    in-flight record (if any) at end-of-input via `finalize`.
    """

    def __new__(cls, rna_to_dna: builtins.bool = True) -> FastaStreamer: ...
    def push(self, chunk: bytes) -> None:
        r"""
        Feed a chunk of bytes. Records that complete inside this chunk are
        queued for `next_record`.
        """

    def next_record(self) -> typing.Optional[tuple[builtins.str, bytes]]:
        r"""
        Pop a completed record from the internal queue.
        """

    def finalize(self) -> None:
        r"""
        Flush the trailing partial line + the in-flight record. Call once after
        the last `push`. The flushed record (if any) is appended to the queue
        — drain with `next_record`.
        """

@typing.final
class FastqStreamer:
    r"""
    Streaming FASTQ parser. 4-line records: `@name`, sequence, `+`, quality.
    Quality scores are consumed and discarded; only `(name, seq)` is yielded.
    """

    def __new__(cls, rna_to_dna: builtins.bool = True) -> FastqStreamer: ...
    def push(self, chunk: bytes) -> None:
        r"""
        Feed a chunk of bytes.
        """

    def next_record(self) -> typing.Optional[tuple[builtins.str, bytes]]:
        r"""
        Pop a completed record from the internal queue.
        """

    def finalize(self) -> None:
        r"""
        Flush the trailing partial line + the in-flight record.
        """

@typing.final
class FastxReader:
    r"""
    A reader for parsing FASTA/FASTQ files.

    The `FastxReader` allows parsing of uncompressed or gzip-compressed
    FASTA/FASTQ files and acts as a Python iterator, yielding sequence records.

    Examples:
        >>> from rammappy import FastxReader
        >>> reader = FastxReader("test.fa")
        >>> for record in reader:
        ...     print(f"{record.name}: {record.sequence}")
    """

    def __new__(cls, path: builtins.str | os.PathLike | pathlib.Path) -> FastxReader:
        r"""
        Open a FASTA/FASTQ file for reading.

        Args:
            path (os.PathLike): The file path to read from. Supports `.gz` compression.

        Returns:
            FastxReader: An iterator over the sequence records.

        Raises:
            IOError: If the file cannot be opened.
        """

    def __iter__(self) -> FastxReader: ...
    def __next__(self) -> typing.Optional[Record]:
        r"""
        Return the next sequence record.

        Yields:
            Record: The sequence record.
        """

    def read_batch(
        self, batch_size: builtins.int
    ) -> tuple[builtins.list[tuple[builtins.str, bytes]], builtins.bool]:
        r"""
        Read sequences until cumulative bases exceed batch_size.
        Returns (seqs, is_eof). Caller can call again for the next batch.
        """

@typing.final
class FilteringParams:
    @property
    def best_n(self) -> builtins.int: ...
    @best_n.setter
    def best_n(self, value: builtins.int) -> None: ...
    @property
    def pri_ratio(self) -> builtins.float: ...
    @pri_ratio.setter
    def pri_ratio(self, value: builtins.float) -> None: ...
    @property
    def mask_level(self) -> builtins.float: ...
    @mask_level.setter
    def mask_level(self, value: builtins.float) -> None: ...
    @property
    def mask_len(self) -> builtins.int: ...
    @mask_len.setter
    def mask_len(self, value: builtins.int) -> None: ...
    @property
    def is_splice(self) -> builtins.bool: ...
    @is_splice.setter
    def is_splice(self, value: builtins.bool) -> None: ...
    @property
    def alt_drop(self) -> builtins.float: ...
    @alt_drop.setter
    def alt_drop(self, value: builtins.float) -> None: ...
    @property
    def seed(self) -> builtins.int: ...
    @seed.setter
    def seed(self, value: builtins.int) -> None: ...
    @property
    def chain_skip_scale(self) -> builtins.float: ...
    @chain_skip_scale.setter
    def chain_skip_scale(self, value: builtins.float) -> None: ...
    @property
    def max_qlen(self) -> builtins.int: ...
    @max_qlen.setter
    def max_qlen(self, value: builtins.int) -> None: ...
    @property
    def jump_min_match(self) -> builtins.int: ...
    @jump_min_match.setter
    def jump_min_match(self, value: builtins.int) -> None: ...

@typing.final
class Index:
    r"""
    The `Index` object represents a genomic sequence index.

    It holds the internal Rust Index for alignment. You can construct an index
    from a collection of sequences, or load it from a previously saved file.

    Examples:
        >>> from rammappy import Index
        >>> index = Index.build([(b"target1", b"ATGC...")])
        >>> index.save("my_index.mmi")
        >>> loaded_index = Index.load("my_index.mmi")
    """

    @property
    def kmer_size(self) -> builtins.int: ...
    @property
    def window_size(self) -> builtins.int: ...
    @property
    def homopolymer_compressed(self) -> builtins.bool: ...
    @property
    def seq_names(self) -> builtins.list[builtins.str]:
        r"""
        Returns the sequence names in the index.

        Returns:
            list[str]: The list of sequence names.
        """

    @staticmethod
    def build(
        seqs: typing.Sequence[tuple[bytes, bytes]],
        w: builtins.int = 10,
        k: builtins.int = 15,
        is_hpc: builtins.bool = False,
        max_occ: builtins.int = 50000,
    ) -> Index:
        r"""
        Build an index from target sequences.

        Args:
            seqs (list[tuple[bytes, bytes]]): A list of tuples containing `(name, sequence)` as bytes.
            w (int): Window size. Defaults to 10.
            k (int): K-mer size. Defaults to 15.
            is_hpc (bool): Homopolymer compressed. Defaults to False.
            max_occ (int): Maximum occurrences. Defaults to 50000.

        Returns:
            Index: The built index.
        """

    @staticmethod
    def load(path: builtins.str | os.PathLike | pathlib.Path) -> Index:
        r"""
        Load an index from file.

        Args:
            path (os.PathLike): The file path to load the index from.

        Returns:
            Index: The loaded index.
        """

    def save(self, path: builtins.str | os.PathLike | pathlib.Path) -> None:
        r"""
        Save the index to a file.

        Args:
            path (os.PathLike): The file path to save the index to.
        """

    def strip_sequences(self) -> None:
        r"""
        Strip sequences from the index to save memory.

        This removes the actual sequence bytes from memory, which is useful when
        you only need to perform mapping and do not need base-level alignment (CIGAR).

        Examples:
            >>> index.strip_sequences()
        """

    def seq(
        self,
        name: builtins.str,
        start: typing.Optional[builtins.int] = None,
        end: typing.Optional[builtins.int] = None,
    ) -> builtins.str:
        r"""
        Returns the sequence for a given target name.

        Args:
            name (str): The name of the target sequence.
            start (int, optional): The 0-based start coordinate. Defaults to 0.
            end (int, optional): The 0-based end coordinate. Defaults to the end of the sequence.

        Returns:
            str: The requested sequence.

        Raises:
            ValueError: If the sequence name is not found in the index.
        """

@typing.final
class MapOptions:
    @property
    def seeding(self) -> SeedingParams: ...
    @seeding.setter
    def seeding(self, value: SeedingParams) -> None: ...
    @property
    def chaining(self) -> ChainingParams: ...
    @chaining.setter
    def chaining(self, value: ChainingParams) -> None: ...
    @property
    def scoring(self) -> ScoringParams: ...
    @scoring.setter
    def scoring(self, value: ScoringParams) -> None: ...
    @property
    def alignment(self) -> AlignmentParams: ...
    @alignment.setter
    def alignment(self, value: AlignmentParams) -> None: ...
    @property
    def filtering(self) -> FilteringParams: ...
    @filtering.setter
    def filtering(self, value: FilteringParams) -> None: ...
    @property
    def pairing(self) -> PairedEndParams: ...
    @pairing.setter
    def pairing(self, value: PairedEndParams) -> None: ...
    @property
    def mini_batch_size(self) -> builtins.int: ...
    @mini_batch_size.setter
    def mini_batch_size(self, value: builtins.int) -> None: ...

@typing.final
class Mapping:
    r"""
    Python representation of an alignment `Mapping`.

    Mappings are lazily evaluated: the actual Rust-level objects are preserved
    until accessed via the Python properties.

    Attributes:
        target_name (bytes): The name of the target sequence.
        target_id (int): Target sequence numeric index.
        target_len (int): Target sequence length.
        target_start (int): Start coordinate on the target.
        target_end (int): End coordinate on the target.
        query_start (int): Start coordinate on the query.
        query_end (int): End coordinate on the query.
        strand (Strand): Orientation of the alignment.
        score (int): Alignment score.
        mapq (int): Mapping quality (0-255).
        is_primary (bool): True if this is the primary alignment.
        is_supplementary (bool): True if this is a supplementary alignment.
        is_spliced (bool): True if this alignment contains splice junctions.
        trans_strand (Strand | None): Transcript strand for splice alignments, if known.
        matches (int): Number of matching bases.
        block_len (int): Alignment block length.
        edit_distance (int): Edit distance (NM tag).
        divergence (float): Sequence divergence (0.0 = identical).
        cigar (bytes | None): The CIGAR string, if requested during alignment.
        cigar_ops (list[CigarElement] | None): Structured CIGAR operations, if requested.
        cs (bytes | None): CS tag string, if requested.
        md (bytes | None): MD tag string, if requested.
    """

    @property
    def target_name(self) -> bytes:
        r"""
        Return the target name as Python `bytes`.
        """

    @property
    def target_start(self) -> builtins.int: ...
    @property
    def target_end(self) -> builtins.int: ...
    @property
    def target_len(self) -> builtins.int: ...
    @property
    def query_start(self) -> builtins.int: ...
    @property
    def query_end(self) -> builtins.int: ...
    @property
    def strand(self) -> Strand: ...
    @property
    def score(self) -> builtins.int: ...
    @property
    def mapq(self) -> builtins.int: ...
    @property
    def is_primary(self) -> builtins.bool: ...
    @property
    def is_supplementary(self) -> builtins.bool: ...
    @property
    def is_spliced(self) -> builtins.bool: ...
    @property
    def trans_strand(self) -> typing.Optional[Strand]: ...
    @property
    def matches(self) -> builtins.int: ...
    @property
    def block_len(self) -> builtins.int: ...
    @property
    def edit_distance(self) -> builtins.int: ...
    @property
    def target_id(self) -> builtins.int: ...
    @property
    def divergence(self) -> builtins.float: ...
    @property
    def cigar(self) -> typing.Optional[bytes]:
        r"""
        Returns the optional CIGAR string as a lazy byte array.
        """

    @property
    def cigar_ops(self) -> typing.Optional[builtins.list[CigarElement]]:
        r"""
        Returns the structured CIGAR operations.
        """

    @property
    def cs(self) -> typing.Optional[bytes]:
        r"""
        Returns the optional cs string as a lazy byte array.
        """

    @property
    def md(self) -> typing.Optional[bytes]:
        r"""
        Returns the optional MD string as a lazy byte array.
        """

    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class MappingIterator:
    r"""
    A lazy iterator that provides `Mapping` objects.

    Instead of allocating a list, we hold an iterator of Rust mappings
    and materialize Python wrapper objects only when requested via `next()`.
    """

    def __iter__(self) -> MappingIterator: ...
    def __next__(self) -> typing.Optional[Mapping]: ...

@typing.final
class Minimizer:
    r"""
    Represents a k-mer sketch (minimizer, syncmer, etc.).

    Contains the genomic coordinate and the hash value.

    Attributes:
        x (int): The 64-bit integer combining the genomic coordinate and other metadata.
        y (int): The 64-bit hash value of the k-mer.
    """

    @property
    def x(self) -> builtins.int: ...
    @property
    def y(self) -> builtins.int: ...

@typing.final
class MinimizerSketcher:
    r"""
    A sketcher that extracts minimizers from sequences.

    Minimizers are the lexicographically smallest k-mers in a sliding window of size w.

    Examples:
        >>> from rammappy.sketch import MinimizerSketcher
        >>> sketcher = MinimizerSketcher(k=15, w=10)
        >>> sketcher.sketch(b"ATGCGTACGATCGATC")
        [<Minimizer object at ...>, ...]
    """

    def __new__(cls, k: builtins.int, w: builtins.int) -> MinimizerSketcher:
        r"""
        Initialize a new MinimizerSketcher.

        Args:
            k (int): The k-mer size.
            w (int): The window size.

        Returns:
            MinimizerSketcher: The initialized sketcher.
        """

    def sketch(self, seq: bytes) -> builtins.list[Minimizer]:
        r"""
        Extract minimizers from a byte string sequence.

        Args:
            seq (bytes): The sequence to sketch.

        Returns:
            list[Minimizer]: A list of minimizer objects.
        """

@typing.final
class PairedEndParams:
    @property
    def max_frag_len(self) -> builtins.int: ...
    @max_frag_len.setter
    def max_frag_len(self, value: builtins.int) -> None: ...
    @property
    def pe_ori(self) -> builtins.int: ...
    @pe_ori.setter
    def pe_ori(self, value: builtins.int) -> None: ...
    @property
    def pe_bonus(self) -> builtins.int: ...
    @pe_bonus.setter
    def pe_bonus(self, value: builtins.int) -> None: ...

@typing.final
class RandstrobeSketcher:
    r"""
    A sketcher that extracts randstrobes from sequences.

    Randstrobes are combinations of k-mers that provide more resilient matching.

    Examples:
        >>> from rammappy.sketch import RandstrobeSketcher
        >>> sketcher = RandstrobeSketcher(k=15, w_min=10, w_max=30)
        >>> sketcher.sketch(b"ATGCGTACGATCGATC")
        [<Minimizer object at ...>, ...]
    """

    def __new__(
        cls, k: builtins.int, w_min: builtins.int, w_max: builtins.int
    ) -> RandstrobeSketcher:
        r"""
        Create a new RandstrobeSketcher.

        Args:
            k (int): The k-mer size.
            w_min (int): The minimum window size.
            w_max (int): The maximum window size.

        Returns:
            RandstrobeSketcher: The initialized sketcher.
        """

    def sketch(self, seq: bytes) -> builtins.list[Minimizer]:
        r"""
        Extract randstrobes from a byte string sequence.

        Args:
            seq (bytes): The sequence to sketch.

        Returns:
            list[Minimizer]: A list of randstrobe objects.
        """

@typing.final
class Record:
    r"""
    A sequence record from a FASTA or FASTQ file.
    """

    @property
    def name(self) -> builtins.str: ...
    @property
    def description(self) -> typing.Optional[builtins.str]: ...
    @property
    def sequence(self) -> bytes: ...
    @property
    def quality(self) -> typing.Optional[bytes]: ...
    def __new__(
        cls,
        name: builtins.str,
        description: typing.Optional[builtins.str],
        sequence: typing.Sequence[builtins.int],
        quality: typing.Optional[typing.Sequence[builtins.int]] = None,
    ) -> Record: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class ScoringParams:
    @property
    def match_score(self) -> builtins.int: ...
    @match_score.setter
    def match_score(self, value: builtins.int) -> None: ...
    @property
    def mismatch_penalty(self) -> builtins.int: ...
    @mismatch_penalty.setter
    def mismatch_penalty(self, value: builtins.int) -> None: ...
    @property
    def gap_open(self) -> builtins.int: ...
    @gap_open.setter
    def gap_open(self, value: builtins.int) -> None: ...
    @property
    def gap_extend(self) -> builtins.int: ...
    @gap_extend.setter
    def gap_extend(self, value: builtins.int) -> None: ...
    @property
    def gap_open2(self) -> builtins.int: ...
    @gap_open2.setter
    def gap_open2(self, value: builtins.int) -> None: ...
    @property
    def gap_extend2(self) -> builtins.int: ...
    @gap_extend2.setter
    def gap_extend2(self, value: builtins.int) -> None: ...
    @property
    def transition(self) -> builtins.int: ...
    @transition.setter
    def transition(self, value: builtins.int) -> None: ...
    @property
    def ambig_penalty(self) -> builtins.int: ...
    @ambig_penalty.setter
    def ambig_penalty(self, value: builtins.int) -> None: ...
    @property
    def noncanon_penalty(self) -> builtins.int: ...
    @noncanon_penalty.setter
    def noncanon_penalty(self, value: builtins.int) -> None: ...
    @property
    def junc_bonus(self) -> builtins.int: ...
    @junc_bonus.setter
    def junc_bonus(self, value: builtins.int) -> None: ...
    @property
    def junc_pen(self) -> builtins.int: ...
    @junc_pen.setter
    def junc_pen(self, value: builtins.int) -> None: ...

@typing.final
class SeedingParams:
    @property
    def mid_occ(self) -> builtins.int: ...
    @mid_occ.setter
    def mid_occ(self, value: builtins.int) -> None: ...
    @property
    def max_occ(self) -> builtins.int: ...
    @max_occ.setter
    def max_occ(self, value: builtins.int) -> None: ...
    @property
    def max_max_occ(self) -> builtins.int: ...
    @max_max_occ.setter
    def max_max_occ(self, value: builtins.int) -> None: ...
    @property
    def occ_dist(self) -> builtins.int: ...
    @occ_dist.setter
    def occ_dist(self, value: builtins.int) -> None: ...
    @property
    def q_occ_frac(self) -> builtins.float: ...
    @q_occ_frac.setter
    def q_occ_frac(self, value: builtins.float) -> None: ...
    @property
    def min_mid_occ(self) -> builtins.int: ...
    @min_mid_occ.setter
    def min_mid_occ(self, value: builtins.int) -> None: ...
    @property
    def max_mid_occ(self) -> builtins.int: ...
    @max_mid_occ.setter
    def max_mid_occ(self, value: builtins.int) -> None: ...

@typing.final
class SyncmerSketcher:
    r"""
    A sketcher that extracts syncmers from sequences.

    Syncmers provide a more evenly spaced sampling of sequences compared to minimizers.

    Examples:
        >>> from rammappy.sketch import SyncmerSketcher
        >>> sketcher = SyncmerSketcher(k=15, s=5)
        >>> sketcher.sketch(b"ATGCGTACGATCGATC")
        [<Minimizer object at ...>, ...]
    """

    def __new__(cls, k: builtins.int, s: builtins.int) -> SyncmerSketcher:
        r"""
        Create a new SyncmerSketcher.

        Args:
            k (int): The k-mer size.
            s (int): The s-mer size.

        Returns:
            SyncmerSketcher: The initialized sketcher.
        """

    def sketch(self, seq: bytes) -> builtins.list[Minimizer]:
        r"""
        Extract syncmers from a byte string sequence.

        Args:
            seq (bytes): The sequence to sketch.

        Returns:
            list[Minimizer]: A list of syncmer objects.
        """

@typing.final
class CigarOp(enum.Enum):
    r"""
    BAM CIGAR operation encodings as a Python Enum.

    The values correspond to the official BAM specification.
    """

    M = ...
    I = ...
    D = ...
    N = ...
    S = ...
    H = ...
    P = ...
    EQ = ...
    X = ...
    B = ...

@typing.final
class Preset(enum.Enum):
    r"""
    The mapping presets available in `rammappy`.

    These presets configure the aligner for different sequencing technologies
    and use cases, tuning heuristics and scoring.

    Examples:
        >>> from rammappy import Index, Aligner, Preset
        >>> index = Index.build([(b"target1", b"ATGC...")])
        >>> aligner = Aligner(index, preset=Preset.MapOnt)
    """

    MapOnt = ...
    MapHifi = ...
    Sr = ...
    Splice = ...
    Asm5 = ...
    Asm10 = ...
    Asm20 = ...
    MapPb = ...

@typing.final
class Strand(enum.Enum):
    r"""
    Strand orientation of an alignment.

    Represents whether the query mapped to the forward or reverse strand of the target.

    Attributes:
        Forward: The forward strand.
        Reverse: The reverse complement strand.
    """

    Forward = ...
    Reverse = ...

def parse_fasta_bytes(data: bytes) -> builtins.list[tuple[builtins.str, bytes]]:
    r"""
    Parse FASTA from a byte slice (works with mmap or regular buffers)
    Returns a list of (name, sequence) pairs.
    """

def read_fasta(
    path: builtins.str | os.PathLike | pathlib.Path,
) -> builtins.list[tuple[builtins.str, bytes]]:
    r"""
    Read all sequences from a FASTA file into memory.
    Returns a list of (name, sequence) pairs.
    """
